name: Deploy VPS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh mankindbr@34.121.162.107 "
            cd ~/barbershop-chatbot &&
            git checkout develop &&
            git pull origin develop &&
            docker-compose -p staging -f docker-compose.staging.yml up -d --build
          "

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh mankindbr@34.121.162.107 "
            cd ~/barbershop-chatbot &&
            git checkout main &&
            git pull origin main &&
            docker-compose -p prod -f docker-compose.prod.yml up -d --build
          "